import AppKit
import Foundation
import Observation

@MainActor
@Observable
final class ClipboardHistoryStore {
    static let maximumItemBytes = 16 * 1_024 * 1_024
    static let defaultItemLimitBytes = 8 * 1_024 * 1_024
    static let persistenceEnabledKey = "OpenFind.clipboardPersistenceEnabledV1"
    static let remoteClipboardType = "com.apple.is-remote-clipboard"
    static let internalPasteboardType = "com.openfind.internal.clipboard"
    static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]
    static let supportedTypes: Set<String> = [
        NSPasteboard.PasteboardType.string.rawValue,
        "public.utf8-plain-text",
        "public.utf16-external-plain-text",
        "public.rtf",
        "public.html",
        "public.url",
        "public.file-url",
        "public.png",
        "public.tiff",
        "public.jpeg",
        "public.heic",
    ]

    @ObservationIgnored let defaults: UserDefaults
    @ObservationIgnored let persistence: any ClipboardHistoryPersisting
    @ObservationIgnored let pasteboard: NSPasteboard
    @ObservationIgnored let contentActionRegistry: ClipboardContentActionRegistry
    @ObservationIgnored let imageTextRecognizer: any ClipboardImageTextRecognizing
    @ObservationIgnored let imageTextRecognitionStartDelay: Duration
    var entries: [ClipboardEntry] = [] {
        didSet { invalidateClipboardProjection() }
    }
    var lastErrorMessage: String?
    var isPersistenceEnabled = true
    var requiresPersistenceMigration = false
    var preferences: ClipboardPreferences {
        didSet { invalidateClipboardProjection() }
    }
    var query = "" {
        didSet {
            if query != oldValue { invalidateClipboardProjection() }
        }
    }
    private(set) var clipboardProjectionRevision: UInt64 = 0
    @ObservationIgnored var cachedClipboardProjectionRevision: UInt64?
    @ObservationIgnored var cachedFilteredEntries: [ClipboardEntry] = []
    @ObservationIgnored var cachedVisibleIndexByID: [UUID: Int] = [:]
    @ObservationIgnored var cachedQuickIndexByID: [UUID: Int] = [:]
    @ObservationIgnored var cachedQuickEntryIDs: [UUID] = []
    @ObservationIgnored var cachedHighlightQuery = ""
    @ObservationIgnored var cachedEntryByID: [UUID: ClipboardEntry] = [:]
    @ObservationIgnored var cachedSnippetKeywords: [(keyword: String, id: UUID)] = []
    @ObservationIgnored var clipboardProjectionBuildCount = 0
    @ObservationIgnored private let rowImageCache: NSCache<NSUUID, NSImage> = {
        let cache = NSCache<NSUUID, NSImage>()
        cache.countLimit = 160
        cache.totalCostLimit = 48 * 1_024 * 1_024
        return cache
    }()
    @ObservationIgnored private let previewImageCache: NSCache<NSUUID, NSImage> = {
        let cache = NSCache<NSUUID, NSImage>()
        cache.countLimit = 16
        cache.totalCostLimit = 192 * 1_024 * 1_024
        return cache
    }()
    @ObservationIgnored private let imageDimensionsCache: NSCache<NSUUID, NSString> = {
        let cache = NSCache<NSUUID, NSString>()
        cache.countLimit = 160
        return cache
    }()
    @ObservationIgnored private let applicationIconCache: NSCache<NSString, NSImage> = {
        let cache = NSCache<NSString, NSImage>()
        cache.countLimit = 96
        return cache
    }()
    @ObservationIgnored var pendingImageTextRecognitionIDs: Set<UUID> = []
    @ObservationIgnored var imageTextRecognitionTask: Task<Void, Never>?
    var selectedIndex = 0
    var selectedEntryIDs: [UUID] = []
    var selectionAnchorID: UUID?
    var pasteStack: ClipboardPasteStack?
    var deletionUndo: ClipboardDeletionUndo?
    var isSearchPresented = false
    var isPreviewVisible = true
    var isActionPanelPresented = false
    var isPanelPresented = false
    var presentationGeneration = 0

    init(
        defaults: UserDefaults = .standard,
        persistence: any ClipboardHistoryPersisting = EncryptedClipboardHistoryPersistence(),
        pasteboard: NSPasteboard = .general,
        contentActionRegistry: ClipboardContentActionRegistry = .standard,
        imageTextRecognizer: any ClipboardImageTextRecognizing =
            VisionClipboardImageTextRecognizer(),
        imageTextRecognitionStartDelay: Duration = .seconds(2)
    ) {
        self.defaults = defaults
        self.persistence = persistence
        self.pasteboard = pasteboard
        self.contentActionRegistry = contentActionRegistry
        self.imageTextRecognizer = imageTextRecognizer
        self.imageTextRecognitionStartDelay = imageTextRecognitionStartDelay
        preferences = ClipboardPreferencesPersistence.load(from: defaults)
        let enabled = defaults.object(forKey: Self.persistenceEnabledKey) as? Bool ?? true
        isPersistenceEnabled = enabled
        requiresPersistenceMigration = enabled && persistence.requiresExplicitMigration
        guard enabled, !requiresPersistenceMigration else { return }
        do {
            entries = try persistence.load()
            let trimmed = trimToLimits()
            if trimmed || normalizePinnedKeys() { persist() }
            enqueueMissingImageTextRecognition()
        } catch {
            entries = []
            lastErrorMessage = error.localizedDescription
        }
    }

    var retentionPeriod: ClipboardRetentionPeriod { preferences.retentionPeriod }
    var itemLimitBytes: Int { preferences.itemLimitBytes }
    var ignoredBundleIdentifiers: Set<String> { preferences.ignoredBundleIdentifiers }
    var pasteWithoutFormatting: Bool { preferences.pasteWithoutFormatting }
    var clearHistoryOnQuit: Bool { preferences.clearHistoryOnQuit }
    var clearSystemClipboardOnQuit: Bool { preferences.clearSystemClipboardOnQuit }
    var fuzzySearchEnabled: Bool { preferences.searchMode == .fuzzy }
    var searchMode: ClipboardSearchMode { preferences.searchMode }
    var clipboardCheckInterval: TimeInterval { preferences.clipboardCheckInterval }
    var retainedStorageBytes: Int { retainedPayloadBytes }
    var canUndoDeletion: Bool { deletionUndo != nil }
    var undoDeletionCount: Int { deletionUndo?.count ?? 0 }
    var highlightQuery: String {
        _ = filteredEntries
        return cachedHighlightQuery
    }
    var hasStructuredSearchFilters: Bool {
        ClipboardStructuredQuery.parse(query).hasFilters
    }

    func rowPreviewImage(for entry: ClipboardEntry) -> NSImage? {
        guard entry.kind == .image else { return nil }
        let key = entry.id as NSUUID
        if let cached = rowImageCache.object(forKey: key) { return cached }
        guard let image = entry.downsampledPreviewImage(maxPixelSize: 256) else { return nil }
        let cost = Int(image.size.width * image.size.height * 4)
        rowImageCache.setObject(image, forKey: key, cost: cost)
        return image
    }

    func entryPreviewImage(for entry: ClipboardEntry) -> NSImage? {
        guard entry.kind == .image else { return nil }
        let key = entry.id as NSUUID
        if let cached = previewImageCache.object(forKey: key) { return cached }
        guard let image = entry.downsampledPreviewImage(maxPixelSize: 1_600) else { return nil }
        let cost = Int(image.size.width * image.size.height * 4)
        previewImageCache.setObject(image, forKey: key, cost: cost)
        return image
    }

    func imageDimensions(for entry: ClipboardEntry) -> String? {
        guard entry.kind == .image else { return nil }
        let key = entry.id as NSUUID
        if let cached = imageDimensionsCache.object(forKey: key) { return cached as String }
        guard let dimensions = entry.imageDimensions else { return nil }
        imageDimensionsCache.setObject(dimensions as NSString, forKey: key)
        return dimensions
    }

    func applicationIcon(for entry: ClipboardEntry) -> NSImage? {
        guard let identifier = entry.sourceBundleIdentifier else { return nil }
        let key = identifier as NSString
        if let cached = applicationIconCache.object(forKey: key) { return cached }
        guard let icon = entry.sourceApplicationIcon else { return nil }
        applicationIconCache.setObject(icon, forKey: key)
        return icon
    }

    private func invalidateClipboardProjection() {
        clipboardProjectionRevision &+= 1
    }

    func beginPresentation() {
        isPanelPresented = true
        isPreviewVisible = true
        isActionPanelPresented = false
        presentationGeneration &+= 1
    }

    func endPresentation() {
        isPanelPresented = false
        isActionPanelPresented = false
        presentationGeneration &+= 1
    }
}
