import AppKit
import Foundation
import Observation

@MainActor
@Observable
final class ClipboardHistoryStore {
    static let maximumEntries = 1_000
    static let maximumItemBytes = 16 * 1_024 * 1_024
    static let maximumHistoryBytes = 48 * 1_024 * 1_024
    static let defaultItemLimitBytes = 8 * 1_024 * 1_024
    static let persistenceEnabledKey = "OpenFind.clipboardPersistenceEnabledV1"
    static let remoteClipboardType = "com.apple.is-remote-clipboard"
    static let internalPasteboardType = "com.openfind.internal.clipboard"
    static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]
    static let supportedTypes: Set<String> = [
        NSPasteboard.PasteboardType.string.rawValue,
        "public.utf8-plain-text",
        "public.utf16-external-plain-text",
        "public.rtf",
        "public.html",
        "public.url",
        "public.file-url",
        "public.png",
        "public.tiff",
        "public.jpeg",
        "public.heic",
    ]

    @ObservationIgnored let defaults: UserDefaults
    @ObservationIgnored let persistence: any ClipboardHistoryPersisting
    @ObservationIgnored let pasteboard: NSPasteboard
    var entries: [ClipboardEntry] = []
    var lastErrorMessage: String?
    var isPersistenceEnabled = true
    var requiresPersistenceMigration = false
    var preferences: ClipboardPreferences
    var query = ""
    var selectedIndex = 0
    var selectedEntryIDs: [UUID] = []
    var selectionAnchorID: UUID?
    var pasteStack: ClipboardPasteStack?
    var isSearchPresented = false
    var isPreviewVisible = false
    var isActionPanelPresented = false
    var isPanelPresented = false
    var presentationGeneration = 0

    init(
        defaults: UserDefaults = .standard,
        persistence: any ClipboardHistoryPersisting = EncryptedClipboardHistoryPersistence(),
        pasteboard: NSPasteboard = .general
    ) {
        self.defaults = defaults
        self.persistence = persistence
        self.pasteboard = pasteboard
        preferences = ClipboardPreferencesPersistence.load(from: defaults)
        let enabled = defaults.object(forKey: Self.persistenceEnabledKey) as? Bool ?? true
        isPersistenceEnabled = enabled
        requiresPersistenceMigration = enabled && persistence.requiresExplicitMigration
        guard enabled, !requiresPersistenceMigration else { return }
        do {
            entries = Array(try persistence.load().prefix(Self.maximumEntries))
            let trimmed = trimToLimits()
            if trimmed || normalizePinnedKeys() { persist() }
        } catch {
            entries = []
            lastErrorMessage = error.localizedDescription
        }
    }

    var retentionPeriod: ClipboardRetentionPeriod { preferences.retentionPeriod }
    var itemLimitBytes: Int { preferences.itemLimitBytes }
    var ignoredBundleIdentifiers: Set<String> { preferences.ignoredBundleIdentifiers }
    var pasteWithoutFormatting: Bool { preferences.pasteWithoutFormatting }
    var clearHistoryOnQuit: Bool { preferences.clearHistoryOnQuit }
    var clearSystemClipboardOnQuit: Bool { preferences.clearSystemClipboardOnQuit }
    var fuzzySearchEnabled: Bool { preferences.searchMode == .fuzzy }
    var searchMode: ClipboardSearchMode { preferences.searchMode }
    var clipboardCheckInterval: TimeInterval { preferences.clipboardCheckInterval }
    var retainedStorageBytes: Int { retainedPayloadBytes }

    func beginPresentation() {
        if trimToLimits() {
            selectedIndex = min(selectedIndex, max(0, filteredEntries.count - 1))
            persist()
        }
        isPanelPresented = true
        isPreviewVisible = false
        isActionPanelPresented = false
        presentationGeneration &+= 1
    }

    func endPresentation() {
        isPanelPresented = false
        isPreviewVisible = false
        isActionPanelPresented = false
        presentationGeneration &+= 1
    }
}
