import AppKit
import Foundation
import Observation

@MainActor
@Observable
final class ClipboardHistoryStore {
    static let maximumItemBytes = 16 * 1_024 * 1_024
    static let defaultItemLimitBytes = 8 * 1_024 * 1_024
    static let persistenceEnabledKey = "OpenFind.clipboardPersistenceEnabledV1"
    static let remoteClipboardType = "com.apple.is-remote-clipboard"
    static let internalPasteboardType = "com.openfind.internal.clipboard"
    static let sourcePasteboardType = "org.nspasteboard.source"
    static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]
    static let supportedTypes: Set<String> = [
        NSPasteboard.PasteboardType.string.rawValue,
        "public.utf8-plain-text",
        "public.utf16-external-plain-text",
        "public.rtf",
        "public.html",
        "public.url",
        "public.file-url",
        "public.png",
        "public.tiff",
        "public.jpeg",
        "public.heic",
    ]

    @ObservationIgnored let defaults: UserDefaults
    @ObservationIgnored let persistence: any ClipboardHistoryPersisting
    @ObservationIgnored let pasteboard: NSPasteboard
    @ObservationIgnored let contentActionRegistry: ClipboardContentActionRegistry
    @ObservationIgnored let imageTextRecognizer: any ClipboardImageTextRecognizing
    @ObservationIgnored let imageTextRecognitionStartDelay: Duration
    @ObservationIgnored let deletionUndoBannerDuration: Duration
    @ObservationIgnored var hasUnpersistedChanges = false
    @ObservationIgnored var suppressEntryDirtyTracking = false
    var entries: [ClipboardEntry] = [] {
        didSet {
            invalidateClipboardProjection()
            if !suppressEntryDirtyTracking { hasUnpersistedChanges = true }
        }
    }
    var lastErrorMessage: String?
    var isPersistenceEnabled = true
    var requiresPersistenceMigration = false
    /// Set when the startup load failed: capture keeps working in memory, but
    /// writing is disabled so the on-disk history cannot be overwritten from
    /// an empty session. Cleared only by relaunching with a successful load.
    private(set) var isPersistenceDegraded = false
    var preferences: ClipboardPreferences {
        didSet { invalidateClipboardProjection() }
    }
    var query = "" {
        didSet {
            if query != oldValue { invalidateClipboardProjection() }
        }
    }
    var kindFilter = ClipboardKindFilter.all {
        didSet {
            guard kindFilter != oldValue else { return }
            selectedIndex = 0
            clearMultiSelection()
            invalidateClipboardProjection()
        }
    }
    private(set) var clipboardProjectionRevision: UInt64 = 0
    @ObservationIgnored var cachedClipboardProjectionRevision: UInt64?
    @ObservationIgnored var cachedFilteredEntries: [ClipboardEntry] = []
    @ObservationIgnored var cachedVisibleIndexByID: [UUID: Int] = [:]
    @ObservationIgnored var cachedQuickIndexByID: [UUID: Int] = [:]
    @ObservationIgnored var cachedQuickEntryIDs: [UUID] = []
    @ObservationIgnored var cachedHighlightQuery = ""
    @ObservationIgnored var cachedSearchPresentationByID: [UUID: ClipboardSearchPresentation] = [:]
    @ObservationIgnored var cachedFrequentEntryIDs: Set<UUID> = []
    @ObservationIgnored var cachedFrequentEntryIDsInOrder: [UUID] = []
    @ObservationIgnored var cachedUsageRankingDate: Date?
    @ObservationIgnored var cachedEntryByID: [UUID: ClipboardEntry] = [:]
    @ObservationIgnored var cachedSnippetKeywords: [(keyword: String, id: UUID)] = []
    @ObservationIgnored var clipboardProjectionBuildCount = 0
    @ObservationIgnored private let rowImageCache: NSCache<NSUUID, NSImage> = {
        let cache = NSCache<NSUUID, NSImage>()
        cache.countLimit = 160
        cache.totalCostLimit = 48 * 1_024 * 1_024
        return cache
    }()
    @ObservationIgnored private let previewImageCache: NSCache<NSUUID, NSImage> = {
        let cache = NSCache<NSUUID, NSImage>()
        cache.countLimit = 16
        cache.totalCostLimit = 192 * 1_024 * 1_024
        return cache
    }()
    @ObservationIgnored private let imageDimensionsCache: NSCache<NSUUID, NSString> = {
        let cache = NSCache<NSUUID, NSString>()
        cache.countLimit = 160
        return cache
    }()
    @ObservationIgnored private let applicationIconCache: NSCache<NSString, NSImage> = {
        let cache = NSCache<NSString, NSImage>()
        cache.countLimit = 96
        return cache
    }()
    @ObservationIgnored var pendingImageTextRecognitionIDs: Set<UUID> = []
    @ObservationIgnored var imageTextRecognitionTask: Task<Void, Never>?
    @ObservationIgnored var previewPresentationTask: Task<Void, Never>?
    @ObservationIgnored var deletionUndoBannerDismissTask: Task<Void, Never>?
    @ObservationIgnored var deletionUndoBannerGeneration: UInt64 = 0
    @ObservationIgnored var nonresidentPayloadEntryIDs: Set<UUID> = []
    @ObservationIgnored var materializedPayloadCache: [UUID: ClipboardEntry] = [:]
    @ObservationIgnored var materializedPayloadCacheOrder: [UUID] = []
    @ObservationIgnored var materializedPayloadCacheBytes = 0
    @ObservationIgnored var isClipboardBackgroundResident = false
    @ObservationIgnored var hasUnpersistedPayloadChanges = false
    var selectedIndex = 0
    var selectedEntryIDs: [UUID] = []
    var selectionAnchorID: UUID?
    var pasteStack: ClipboardPasteStack?
    var deletionUndo: ClipboardDeletionUndo?
    var isDeletionUndoBannerPresented = false
    var isSearchPresented = false
    var isPreviewVisible = true
    var isActionPanelPresented = false
    var isPanelPresented = false
    var presentationGeneration = 0

    init(
        defaults: UserDefaults = .standard,
        persistence: any ClipboardHistoryPersisting = EncryptedClipboardHistoryPersistence(),
        pasteboard: NSPasteboard = .general,
        contentActionRegistry: ClipboardContentActionRegistry = .standard,
        imageTextRecognizer: any ClipboardImageTextRecognizing =
            VisionClipboardImageTextRecognizer(),
        imageTextRecognitionStartDelay: Duration = .seconds(2),
        deletionUndoBannerDuration: Duration = .seconds(5)
    ) {
        self.defaults = defaults
        self.persistence = persistence
        self.pasteboard = pasteboard
        self.contentActionRegistry = contentActionRegistry
        self.imageTextRecognizer = imageTextRecognizer
        self.imageTextRecognitionStartDelay = imageTextRecognitionStartDelay
        self.deletionUndoBannerDuration = deletionUndoBannerDuration
        preferences = ClipboardPreferencesPersistence.load(from: defaults)
        let enabled = defaults.object(forKey: Self.persistenceEnabledKey) as? Bool ?? true
        isPersistenceEnabled = enabled
        let migrationRequired = enabled && persistence.requiresExplicitMigration
        requiresPersistenceMigration = migrationRequired
        guard enabled,
              !migrationRequired || persistence.hasRecoverableDatabase else { return }
        do {
            entries = try persistence.loadResidentHistory()
            nonresidentPayloadEntryIDs = persistence.unloadedPayloadEntryIDs
            // A populated v3 database can finish the key commit on its own;
            // only a legacy-only store should remain behind the explicit
            // migration button.
            requiresPersistenceMigration = false
            let trimmed = trimToLimits()
            let normalizedKinds = normalizeContentKinds()
            let normalizedPins = normalizePinnedKeys()
            if trimmed || normalizedKinds || normalizedPins {
                _ = persist()
            } else {
                hasUnpersistedChanges = false
            }
            enqueueMissingImageTextRecognition()
        } catch {
            if migrationRequired {
                // Keep the explicit-migration surface available if the
                // crash-window recovery cannot authenticate the database.
                lastErrorMessage = error.localizedDescription
                return
            }
            // A transient load failure must degrade this session to
            // memory-only capture: any later persist would rewrite the store
            // from the empty in-memory state and permanently delete every
            // entry still safe on disk. The persistence layer enforces the
            // same rule independently.
            entries = []
            isPersistenceDegraded = true
            lastErrorMessage = error.localizedDescription
        }
    }

    var retentionPeriod: ClipboardRetentionPeriod { preferences.retentionPeriod }
    var itemLimitBytes: Int { preferences.itemLimitBytes }
    var ignoredBundleIdentifiers: Set<String> { preferences.ignoredBundleIdentifiers }
    var pasteWithoutFormatting: Bool { preferences.pasteWithoutFormatting }
    var clearHistoryOnQuit: Bool { preferences.clearHistoryOnQuit }
    var clearSystemClipboardOnQuit: Bool { preferences.clearSystemClipboardOnQuit }
    var fuzzySearchEnabled: Bool { preferences.searchMode == .fuzzy }
    var searchMode: ClipboardSearchMode { preferences.searchMode }
    var clipboardCheckInterval: TimeInterval { preferences.clipboardCheckInterval }
    var retainedStorageBytes: Int { retainedPayloadBytes }
    var canUndoDeletion: Bool { deletionUndo != nil }
    var undoDeletionCount: Int { deletionUndo?.count ?? 0 }
    var highlightQuery: String {
        _ = filteredEntries
        return cachedHighlightQuery
    }
    var hasStructuredSearchFilters: Bool {
        ClipboardStructuredQuery.parse(query).hasFilters
    }

    func rowPreviewImage(for entry: ClipboardEntry) -> NSImage? {
        guard entry.kind == .image else { return nil }
        let key = entry.id as NSUUID
        if let cached = rowImageCache.object(forKey: key) { return cached }
        let materialized = (try? materializedEntry(for: entry)) ?? entry
        guard let image = materialized.downsampledPreviewImage(maxPixelSize: 256) else {
            return nil
        }
        let cost = Int(image.size.width * image.size.height * 4)
        rowImageCache.setObject(image, forKey: key, cost: cost)
        return image
    }

    func entryPreviewImage(for entry: ClipboardEntry) -> NSImage? {
        guard entry.kind == .image else { return nil }
        let key = entry.id as NSUUID
        if let cached = previewImageCache.object(forKey: key) { return cached }
        let materialized = (try? materializedEntry(for: entry)) ?? entry
        guard let image = materialized.downsampledPreviewImage(maxPixelSize: 1_600) else {
            return nil
        }
        let cost = Int(image.size.width * image.size.height * 4)
        previewImageCache.setObject(image, forKey: key, cost: cost)
        return image
    }

    func imageDimensions(for entry: ClipboardEntry) -> String? {
        guard entry.kind == .image else { return nil }
        let key = entry.id as NSUUID
        if let cached = imageDimensionsCache.object(forKey: key) { return cached as String }
        let materialized = (try? materializedEntry(for: entry)) ?? entry
        guard let dimensions = materialized.imageDimensions else { return nil }
        imageDimensionsCache.setObject(dimensions as NSString, forKey: key)
        return dimensions
    }

    func applicationIcon(for entry: ClipboardEntry) -> NSImage? {
        guard let identifier = entry.sourceBundleIdentifier else { return nil }
        let key = identifier as NSString
        if let cached = applicationIconCache.object(forKey: key) { return cached }
        guard let icon = entry.sourceApplicationIcon else { return nil }
        applicationIconCache.setObject(icon, forKey: key)
        return icon
    }

    private func invalidateClipboardProjection() {
        clipboardProjectionRevision &+= 1
    }

    func releasePresentationCachesForBackground() {
        rowImageCache.removeAllObjects()
        previewImageCache.removeAllObjects()
        imageDimensionsCache.removeAllObjects()
        applicationIconCache.removeAllObjects()
        cachedClipboardProjectionRevision = nil
        cachedFilteredEntries.removeAll(keepingCapacity: false)
        cachedVisibleIndexByID.removeAll(keepingCapacity: false)
        cachedQuickIndexByID.removeAll(keepingCapacity: false)
        cachedQuickEntryIDs.removeAll(keepingCapacity: false)
        cachedSearchPresentationByID.removeAll(keepingCapacity: false)
        cachedFrequentEntryIDs.removeAll(keepingCapacity: false)
        cachedFrequentEntryIDsInOrder.removeAll(keepingCapacity: false)
        cachedEntryByID.removeAll(keepingCapacity: false)
        cachedSnippetKeywords.removeAll(keepingCapacity: false)
        cachedUsageRankingDate = nil
        invalidateClipboardProjection()
    }

    func beginPresentation() {
        resumePayloadsForPresentation()
        previewPresentationTask?.cancel()
        previewPresentationTask = nil
        // Refresh time-decayed usage periodically without throwing away the
        // warm projection on every open; opening the panel must stay instant.
        if let cachedUsageRankingDate,
           Date().timeIntervalSince(cachedUsageRankingDate) >= 60 * 60 {
            invalidateClipboardProjection()
        }
        isPanelPresented = true
        isPreviewVisible = false
        isActionPanelPresented = false
        presentationGeneration &+= 1

        guard preferences.openPreviewAutomatically else { return }
        let generation = presentationGeneration
        let delay = max(0, preferences.previewDelayMilliseconds)
        previewPresentationTask = Task { @MainActor [weak self] in
            try? await Task.sleep(for: .milliseconds(delay))
            guard let self,
                  !Task.isCancelled,
                  self.isPanelPresented,
                  self.presentationGeneration == generation else { return }
            self.isPreviewVisible = true
            self.previewPresentationTask = nil
            self.presentationGeneration &+= 1
        }
    }

    func endPresentation() {
        previewPresentationTask?.cancel()
        previewPresentationTask = nil
        isPanelPresented = false
        isActionPanelPresented = false
        presentationGeneration &+= 1
    }
}
